# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --production --frozen-lockfile

      # Runs a single command using the runners shell
      - name: Compile SASS
        run: yarn css

      # Deploys the compiled CSS file
      - name: Deploy CSS via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.japebe.de
          username: u514200084.admin
          password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
          local-dir: out/
          server-dir: custom-styles/
